### ISSUE TITLE
不解锁cfg和dmvt将不可用

### ISSUE THREAD

**Issue by FIU001** [tmbt78/Huawei-Matebook-X-2020-Hackintosh#1]
期待得到您的回复，我将用于和您同机型的matebookX2020，我不想修改bios，解锁cfg和dmvt，用了这个EFI之后卡进度条，请教我该如何操作，用在的我电脑上

**Comment by tmbt78** [comment]
Hi,
replace the original config.plist in OC folder with this one and let me know if it worked.


Mattia

[config.plist.zip](https://github.com/tmbt78/Huawei-Matebook-X-2020-Hackintosh/files/6617744/config.plist.zip)

**Comment by FIU001** [comment]
好的 我将尽快测试

**Comment by FIU001** [comment]
很遗憾，会卡在进度条的三分之一处，我目前已经安装的是11.3.0版本，用这个文件进不去，不知道下面这个会不会有所参考
![WangWang20210609004811](https://user-images.githubusercontent.com/34433756/121226529-4102aa80-c8bd-11eb-9b6b-95d6a7cca298.jpg)

**Comment by tmbt78** [comment]
Hi,
it's quite strange ... are you sure you've this laptop model ?
Is your bios at version 1.04 ?

I will update my EFI soon because i've made some changes and upgraded to latest version of OC.
You could try this new EFI. In the EFI there will be two config.plist (one with cfg and DMVT patch disable and one with them enable. You've to use the second one because you don't have a modded bios).

**Comment by FIU001** [comment]
好的，期待您的更新

**Comment by tmbt78** [comment]
Done.
please remember also to rename the config.plist to use the other one and remember to insert your personal data in PlatformInfo section
